
version: '3.8'
services:
    app:
        build: 
            context: .
        volumes: 
            - .:/client-project
        ports:
            - 3001:3000
        environment:
             - REACT_APP_DEV=yes
        image: app:react
        container_name: sample
        command: npm start